Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Demo.PL.Helper;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Demo.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IDapartmentRepository _departmentRepository;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
;
            _unitOfWork=unitOfWork;
            _mapper = mapper;

        }
        public async Task<IActionResult> Index(string SearchInput)
        {
            var employees = Enumerable.Empty<Employee>();

            if (string.IsNullOrEmpty(SearchInput))
            {
                 employees = await _unitOfWork.EmployeeRepository.GetAll();

            }
            else
            {
                 employees = await _unitOfWork.EmployeeRepository.GetByNAme(SearchInput.ToLower());

            }

           var result = _mapper.Map<IEnumerable<EmployeeViewModel>>( employees);
            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeViewModel)
        {

            if (ModelState.IsValid)
            {
                employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "images");
                var model = _mapper.Map<Employee>(employeeViewModel);

                  _unitOfWork.EmployeeRepository.Add(model);
                var count = await _unitOfWork.Complete();
                if (count > 0)
                {
                    TempData["Message"] = "Employee Added";
                }
                else 
                {
                    TempData["Message"] = "Employee Not Added";

                }

                return RedirectToAction("Index");

            }

            return View();
        }
        [HttpGet]
        public Task<IActionResult> Update(int? Id)
        {

            return Details(Id, nameof(Update));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromRoute] int? Id, EmployeeViewModel employeeViewModel)
        {
            if (Id != employeeViewModel.Id)
                return BadRequest();

            if(employeeViewModel.ImageName is not null)
            {
                DocumentSettings.DeleteFile(employeeViewModel.ImageName, "images");
            }
            employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "images");


            var result = _mapper.Map<Employee>(employeeViewModel);



            if (ModelState.IsValid)
            {
                 _unitOfWork.EmployeeRepository.Update(result);
                var count = await _unitOfWork.Complete();
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(employeeViewModel);
        }
        [HttpGet]
        public Task<IActionResult> Delete(int? Id)
        {
            return Details(Id, nameof(Delete));

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int? Id, EmployeeViewModel employeeViewModel)
        {
            if (Id != employeeViewModel.Id)
                return BadRequest();
            var result = _mapper.Map<Employee>(employeeViewModel);

            if (ModelState.IsValid)
            {
                _unitOfWork.EmployeeRepository.Delete(result);
                var count = await _unitOfWork.Complete();
                if (count > 0)
                {
                    DocumentSettings.DeleteFile(employeeViewModel.ImageName, "images");

                    return RedirectToAction(nameof(Index));
                }
            }
            return View(employeeViewModel);
        }
        public async Task<IActionResult> Details(int? Id, string ViewName = "Details")
        {
            if (Id is null)
                return BadRequest();

            var employee = await _unitOfWork.EmployeeRepository.Get(Id.Value);
            var result = _mapper.Map<EmployeeViewModel>(employee);

            if (employee is null)
                return NotFound();

            return View(ViewName, result);

        }
    }
}

Demo.PL/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]

    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public RoleController( RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager,IMapper mapper)
        {
            _roleManger = roleManager;
            _userManager = userManager;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string RoleSearchInput)
        {
            var roles = Enumerable.Empty<RoleViewModel>();

            if (string.IsNullOrEmpty(RoleSearchInput))
            {
                roles = await _roleManger.Roles.Select(R => new RoleViewModel()
                {
                    ID = R.Id,
                    RoleName = R.Name,
                }).ToListAsync();
            }
            else
            {
                roles = await _roleManger.Roles.Where(R => R.Name
                                                .ToLower()
                                                .Contains(RoleSearchInput.ToLower()))
                                                .Select(R => new RoleViewModel()
                                                {
                                                    ID = R.Id,
                                                    RoleName = R.Name,
                                                }).ToListAsync();
            }

            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole()
                {
                    Name = model.RoleName
                };
                var result =  await _roleManger.CreateAsync(role);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, "failed ");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromRoute] string id, RoleViewModel model)
        {
            if (id != model.ID)
                return BadRequest();

            //if (employee.ImageName is not null)
            //{
            //    DocumentSettings.DeleteFile(employee.ImageName, "images");
            //}
            //employee.ImageName = DocumentSettings.UploadFile(employee.Image, "images");


            if (ModelState.IsValid)
            {
                var roleFromDB = await _roleManger.FindByIdAsync(id);
                if (roleFromDB is null)
                    return NotFound();

                //var usesViewModel = _mapper.Map<ApplicationUser>(model);
                // update manual 

                roleFromDB.Name = model.RoleName;
                

                var result = await _roleManger.UpdateAsync(roleFromDB);


                //int count = _employeeRepository.Update(employeeViewModel);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Update(string id) => await Details(id, "Update");


        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest(); // Error 400

            var roleFromDB = await _roleManger.FindByIdAsync(id);
            if (roleFromDB is null)
                return NotFound();

            var role = _mapper.Map<RoleViewModel>(roleFromDB);

            return View(ViewName, role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, RoleViewModel model)
        {
            if (id != model.ID)
                return BadRequest();

            //if (employee.ImageName is not null)
            //{
            //    DocumentSettings.DeleteFile(employee.ImageName, "images");
            //}
            //employee.ImageName = DocumentSettings.UploadFile(employee.Image, "images");


            if (ModelState.IsValid)
            {
                var roleFromDB = await _roleManger.FindByIdAsync(id);
                if (roleFromDB is null)
                    return NotFound();

                //var usesViewModel = _mapper.Map<ApplicationUser>(model);
                // update manual 



                var result = await _roleManger.DeleteAsync(roleFromDB);


                //int count = _employeeRepository.Update(employeeViewModel);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id) => await Details(id, "Delete");

        public async Task<IActionResult> AddOrRemoveUser(string roleId)
        {

           var role =await _roleManger.FindByIdAsync(roleId);
           if(role is null)
                return NotFound();
            ViewData["RoleId"] = roleId;
            ViewData["RoleName"] = role.Name;
           var UsersInRole = new List<UsersInRoleViewModel>();
           var UserInDB = await _userManager.Users.ToListAsync();
            foreach (var user in UserInDB)
            {
                var UserInRole = new UsersInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                    UserInRole.IsSelected = true;
                else
                    UserInRole.IsSelected = false;

                UsersInRole.Add(UserInRole);
            }
            return View(UsersInRole);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUser(string roleId , List<UsersInRoleViewModel> users)
        {
            var role = await _roleManger.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();
            if(ModelState.IsValid)
            {
                foreach(var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if(appUser is not null)
                    {
                        if (user.IsSelected && ! await _userManager.IsInRoleAsync(appUser,role.Name))
                        {
                            await _userManager.AddToRoleAsync(appUser,role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);

                        }
                    }
                   
                }
                return RedirectToAction(nameof(Update) , new {id = roleId});

            }

            return View(users);
        }
    }
}

Demo.PL/Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.Helper;
using Demo.PL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager , IMapper mapper)
        {
            _userManager = userManager;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string UserSearchInput)
        {
            var users = Enumerable.Empty<UserViewModel>();

            if (string.IsNullOrEmpty(UserSearchInput))
            {
                users = await _userManager.Users.Select(U => new UserViewModel()
                {
                    Id = U.Id,
                    FirstName = U.FirstName,
                    LastName = U.LastName,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result

                }).ToListAsync();
            }
            else
            {
                users = await _userManager.Users.Where(U => U.Email
                                                .ToLower()
                                                .Contains(UserSearchInput.ToLower()))
                                                .Select(U => new UserViewModel()
                                                {
                                                    Id = U.Id,
                                                    FirstName = U.FirstName,
                                                    LastName = U.LastName,
                                                    Email = U.Email,
                                                    Roles = _userManager.GetRolesAsync(U).Result
                                                }).ToListAsync();

                TempData["data"]=users;
            }

            return View(users);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromRoute] string id, UserViewModel model)
        {
            if (id != model.Id)
                return BadRequest();

            //if (employee.ImageName is not null)
            //{
            //    DocumentSettings.DeleteFile(employee.ImageName, "images");
            //}
            //employee.ImageName = DocumentSettings.UploadFile(employee.Image, "images");


            if (ModelState.IsValid)
            {
                var userFromDB = await _userManager.FindByIdAsync(id);
                if(userFromDB is null)
                    return NotFound ();

                //var usesViewModel = _mapper.Map<ApplicationUser>(model);
                // update manual 

                userFromDB.FirstName = model.FirstName;
                userFromDB.LastName = model.LastName;
                userFromDB.Email = model.Email;

               var result = await _userManager.UpdateAsync(userFromDB);


                //int count = _employeeRepository.Update(employeeViewModel);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Update(string id) => await Details(id, "Update");



        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest(); // Error 400

           var userFromDB = await _userManager.FindByIdAsync(id);
            if (userFromDB is null)
                return NotFound();

            var user = _mapper.Map<UserViewModel>(userFromDB);

            return View(ViewName, user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, UserViewModel model)
        {
            if (id != model.Id)
                return BadRequest();

            //if (employee.ImageName is not null)
            //{
            //    DocumentSettings.DeleteFile(employee.ImageName, "images");
            //}
            //employee.ImageName = DocumentSettings.UploadFile(employee.Image, "images");


            if (ModelState.IsValid)
            {
                var userFromDB = await _userManager.FindByIdAsync(id);
                if (userFromDB is null)
                    return NotFound();

                //var usesViewModel = _mapper.Map<ApplicationUser>(model);
                // update manual 

           

                var result = await _userManager.DeleteAsync(userFromDB);


                //int count = _employeeRepository.Update(employeeViewModel);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id) => await Details(id, "Delete");
    }
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> @ViewData["Title"] Form </title>
        <link href="~/css/Auth.css" rel="stylesheet" />
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />


    </head>
    <body>
        <div class="wrapper" >
        @RenderBody()
        </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        @await RenderSectionAsync("ValidationSection", required :false)
    </body>


</html>

Demo.PL/Views/Shared/_ButtonPartialView.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fa fa-eye"></i>Details
    </a>
</td>
<td>
    <a asp-action="Update" asp-route-id="@Model" class="btn btn-success">
        <i class="fa fa-edit"></i> Update
    </a>
</td>
<td>
    <a  asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fa fa-trash"></i> Delete
    </a>
</td>

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        
                        
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationSection", required: false)
</body>
</html>